-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LIBRERIA` DEFAULT CHARACTER SET UTF8MB4;

USE `LIBRERIA`;

-- -----------------------------------------------------
-- Table `libreria`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LIBRERIA`.`USUARIOS` (
  `IDUSUARIOS` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBREUSUARIO` VARCHAR(45) NOT NULL,
  `CLAVE` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `APELLIDO` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUSUARIOS`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8 ROW_FORMAT = DYNAMIC;

-- -----------------------------------------------------
-- Table `libreria`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LIBRERIA`.`LIBROS` (
  `ISBN` INT(11) NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `AUTOR` VARCHAR(45) NOT NULL,
  `GENERO` VARCHAR(45) NOT NULL,
  `ALQUILADO` BOOLEAN NULL DEFAULT FALSE,
  `USUARIOALQUILA` INT(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `FK_LIBROS_USUARIOS_IDX` (`USUARIOALQUILA` ASC) VISIBLE,
  CONSTRAINT `USUARIOALQUILA` FOREIGN KEY (`USUARIOALQUILA`) REFERENCES `LIBRERIA`.`USUARIOS` (`IDUSUARIOS`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB AUTO_INCREMENT = 2 DEFAULT CHARACTER SET = UTF8;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;